version: $(frameworkVersion).{build}
dotnet_csproj:
   patch: true
   file: '**\*.csproj'
   version: $(frameworkVersion)
   package_version: $(frameworkVersion)
   assembly_version: $(frameworkVersion)
   file_version: '{version}'
   informational_version: '{version}'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(frameworkVersion)
  assembly_file_version: '{version}'
  assembly_informational_version: $(frameworkVersion)
environment:
  frameworkVersion: 1.0.0
before_build:
 - dotnet restore
 - nuget restore
build:
  project: Ocaramba.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.ProjectExample.*.dll'
after_test:
- ps: >-
    7z a testresults.zip .\Ocaramba.ProjectExample.*\bin\Release\**\*.png

    7z a testresults.zip .\Ocaramba.ProjectExample.*\bin\Release\**\*.html

    7z a testresults.zip .\Ocaramba.ProjectExample.*\bin\Release\**\*.log

    appveyor PushArtifact testresults.zip

    appveyor PushArtifact .\OcarambaTemplatesVSIX\bin\Release\*.vsix
