version: $(frameworkVersion).{build}
environment:
  frameworkVersion: 1.0.0
configuration: Release
before_build:
 - dotnet restore
 - nuget restore
build:
  project: Ocaramba.templates.sln
  verbosity: minimal
test:
  # only assemblies to test
  assemblies:
    only:
      - '**\Ocaramba.ProjectExample.*.dll'
artifacts:
  - path: .\**\*.vsix
    name: Template
