# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  templateVersion: '1.6'
  OcarambaVersion: '3.2.9'
  AppveyorTestLoggerVersion: '2.0.0'
  MicrosoftNetTestSdkVersion: '16.5.0'
  SeleniumWebdriverChromeDriverVersion: '80.0.3987.10601'
  NpoiVersion: '2.4.1'

steps:
- task: PowerShell@2
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    targetType: 'inline'
    script: |
      $tags = git tag --sort=-creatordate   
      $tag = $tags[0]
      Write-Host "##vso[task.setvariable variable=templateVersion]$tag"

- task: PowerShell@2
  inputs:
    filePath: './setPackagesVersions.ps1'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: './Ocaramba.Templates.VSIX/packages.config'
    feedsToUse: 'select'
    restoreDirectory: '../packages'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.*
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    Configuration: '$(buildConfiguration)'
    VersionNumber: '$(templateVersion)'
    FileVersionNumber: '$(templateVersion).$(Build.BuildId)'
    InformationalVersion: '$(templateVersion)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/v:minimal'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './Ocaramba.Templates.VSIX/bin/Release/Ocaramba.Templates.vsix'
    artifact: 'Template'
    publishLocation: 'pipeline'
