# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
  templateVersion: '1.9.4'
  OcarambaVersion: '3.3.0'
  
  SeleniumWebDriverVersion: '3.141.0'
  SeleniumSupportVersion: '3.141.0'
  
  SeleniumWebdriverChromeDriverVersion: '91.0.4472.10100'
  SeleniumWebDriverGeckoDriverVersion: '0.29.1'
  SeleniumWebDriverIEDriverVersion: '3.150.1.2'
  
  NUnitVersion: '3.13.2'
  NUnit3TestAdapterVersion: '4.0.0'

  MicrosoftNetTestSdkVersion: '16.8.3'
  MSTestTestAdapterVersion: '2.2.4'
  MSTestTestFrameworkVersion: '2.2.4'
  
  NPOIVersion: '2.5.3'
  NLogVersion: '4.7.10'

steps:
- task: PowerShell@2
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    targetType: 'inline'
    script: |
      $tags = git tag --sort=-creatordate   
      $tag = $tags[0]
      Write-Host "##vso[task.setvariable variable=templateVersion]$tag"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '((Get-Content -path ./Ocaramba.Templates.VSIX/source.extension.vsixmanifest -Raw) -replace ''Version="\d\.\d.\d" Language'',''Version="$(templateVersion)" Language'') | Set-Content -Path ./Ocaramba.Templates.VSIX/source.extension.vsixmanifest'
- task: PowerShell@2
  inputs:
    filePath: './setPackagesVersions.ps1'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: './Ocaramba.Templates.VSIX/Ocaramba.Templates.csproj'
    feedsToUse: 'select'
    restoreDirectory: '../packages'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.*
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    Configuration: '$(buildConfiguration)'
    VersionNumber: '$(templateVersion)'
    FileVersionNumber: '$(templateVersion).$(Build.BuildId)'
    InformationalVersion: '$(templateVersion)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/v:minimal'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './Ocaramba.Templates.VSIX/bin/Release/Ocaramba.Templates.vsix'
    artifact: 'Template'
    publishLocation: 'pipeline'

- task: GitHubRelease@1
  condition: and(succeeded(),startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  inputs:
    gitHubConnection: 'OcaramabaTemplateRelease'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    tagSource: 'gitTag'
    tagPattern: '\d\.\d.\d'
    target: '$(Build.SourceVersion)'
    tag: '$(templateVersion)'
    title: 'Version $(templateVersion)'
    changeLogCompareToRelease: 'lastNonDraftReleaseByTag'
    changeLogType: 'commitBased'
